Homework 05
Otus-DevOps-2017-11/Maksov_Infra pull request #1
Opened 2017-12-24 16:21 UTC by Maksov

Request содержит результаты выполнения домашней работы № 5
1. Файл setupvpn.sh - скрипт для установки VPN сервера Pritunl и базы данных MongoDB
VPN сервер
Сеть  192.168.222.0/24
Порт 11465
2. Файл Otus_test_Otus_Server.ovpn - файл конфигурации для vpn-клиента
Пользователь test
IP адрес клиента 192.168.222.2
3. Файл README.md
-- Описание конфигураций хоста bastion и internalhost
-- Описание способа подключения к хосту за шлюзом в одну команду 
-- Описание способа подключения к хосту за шлюзом по имени хоста

2017-12-25 15:44 UTC, Nklya requested changes
Добрый вечер.

Максим, все сделано отлично, но почему VPN сервер погашен?
В ДЗ явно говорилось, что выключать его нужно после аппрува PR.

Запусти VPN, напиши комментарий в этом PR  и я повторно проверю его.

2017-12-26 10:52 UTC, Maksov commented
Немного пропустил этот момент) Запустил VPN сервер. https://35.205.192.125/.

2017-12-26 10:59 UTC, Nklya commented
А какой теперь IP у  internalhost?
Те, которые указаны в ридми. 10.132.0.3 не пингуется. И 10.132.0.2 тоже.

Смысл состоял в том, что после подключения по VPN должен быть доступен internalhost, у которого нет внешнего адреса.

2017-12-26 11:48 UTC, Maksov commented
Да, понимаю. Экспериментировал. Роутинг убрал. Сейчас повторно добавил. Проверил. Должно пинговаться

2017-12-26 12:11 UTC, Nklya approved these changes
Добрый день.

Максим, условия ДЗ выполнены, описание в ридми добавлено отличное, VPN работает.

Еще интересный пример динамического подключения через джамп хост с магией на sed и nc, которая позволяет делать такое ssh host1+host2
https://wiki.gentoo.org/wiki/SSH_jump_host#Dynamic_jumphost_list

Не забудь удалить хосты и постоянный IP адрес.

2017-12-26 12:20 UTC, merged