Homework 12
Otus-DevOps-2017-11/Maksov_Infra pull request #8
Opened 2018-01-23 13:00 UTC by Maksov

1. PR содержит результаты домашнего задания № 12 Ansible: работа с
ролями и окружениями
2. Результаты
- созданы роли app и db
- созданы окружения prod  stage
- использование комьюнити ролей (nginx)
- настройка динамического инвентори для окружений
- настройка packer validate, terraform validate, ansible_lint в travis

2018-01-23 18:03 UTC, Nklya requested changes
Добрый вечер.

Максим, в общем есть куча замечаний.
1. Почему в этом PR меняются файлы из тераформа и пакера?
2. Почему куча остатков от неразрешенных конфликтов?
3. Ты удаляешь конфигурацию тревиса в этом PR
4. И жуткая дичь в плейбуках.

Нужно:
1. Вычистить остатки кривых мержей
2. Убрать всю эту дичь из плейбуков. Это просто идеальный пример как не надо делать. Я привел пример, как в плейбуке можно указать несколько групп, к которым он применяется.
3. Сделать так, чтобы тревис не исчезал внезапно в этом PR
4. Больше никогда не править не относящиеся к PR файлы. Хочешь править - отдельный PR или прямо в мастер, что больше нравится.

2018-01-23 18:03 UTC, Nklya commented on ansible/playbooks/app.yml
> +  vars_files:
А это еще зачем?

2018-01-23 18:03 UTC, Nklya commented on ansible/playbooks/db.yml
> +  vars_files:
А это еще зачем?

2018-01-23 18:03 UTC, Nklya commented on ansible/playbooks/deploy.yml
> +  vars_files:
А это еще зачем?

2018-01-23 18:03 UTC, Nklya commented on ansible/playbooks/group_app_hosts
> +group_app_hosts: tag_prod-app
Это еще зачем?

2018-01-23 18:03 UTC, Nklya commented on .travis.yml
> -language: bash
В этом PR ты удаляешь .travis.yml и мейкфайл, если ты не заметил.

2018-01-23 18:03 UTC, Nklya commented on Makefile
> -	cd $(GIT_DIR)/ansible && find . -type f -name "*.yml" -exec ansible-lint {} -q \; || exit 1;
Не особо хорошая идея гнать линтер по всем ямлам.
Достаточно по site.yml, а он уже инклудит остальное.

2018-01-23 18:03 UTC, Nklya commented on packer/db.json
> +<<<<<<< HEAD
Почему конфликты криво пофикшены?

2018-01-23 18:03 UTC, Nklya commented on terraform/modules/db/outputs.tf
> +<<<<<<< HEAD
Почему конфликты криво пофикшены?

2018-01-23 18:03 UTC, Nklya commented on ansible/playbooks/deploy.yml
> +  hosts: "{{ group_app_hosts }}"
Зачем эта дичь, если можно было просто вот так сделать?
```
hosts:
     - app
     - tag_prod-app
     - tag_stage-app
```

И так везде.

2018-01-23 18:03 UTC, Nklya commented on ansible/set_env.sh
> +#!/bin/bash
Вместо того, чтобы указывать `-i environment/prod` ты городишь просто кучу костылей.

2018-01-23 18:03 UTC, Nklya commented on packer/scripts/install_ruby.sh
> +apt install python-apt
А это зачем?

2018-01-23 18:03 UTC, Nklya commented on terraform/modules/db/variables.tf
> +<<<<<<< HEAD
Почему конфликты криво пофикшены?

2018-01-23 21:09 UTC, Maksov commented on ansible/playbooks/deploy.yml
> +  hosts: "{{ group_app_hosts }}"
@Nklya в readme описывал. когда он обращаться будет к динамическому инвентори, он поставит и на tag_prod-app и на tag_stage-app. чтоб разделить и тестовое окружение и продакшн

2018-01-23 21:12 UTC, Nklya commented on ansible/playbooks/deploy.yml
> +  hosts: "{{ group_app_hosts }}"
Смысл состоит как раз в том, что код ансибла у нас должен быть одинаковый для разных окружений. А кастомизируем мы их с помощью различных переменных.

2018-01-23 21:12 UTC, Maksov commented on packer/scripts/install_ruby.sh
> +apt install python-apt
@Nklya nginx ругался. поставил в сборку.

2018-01-23 21:14 UTC, Maksov commented on Makefile
> -	cd $(GIT_DIR)/ansible && find . -type f -name "*.yml" -exec ansible-lint {} -q \; || exit 1;
@Nklya ну как то я экспериментировал с кривыми playbook. он не вывел ошибок.

2018-01-23 21:22 UTC, Maksov commented on ansible/set_env.sh
> +#!/bin/bash
@Nklya чтоб запускать только команду запуска playbook. не отрицаю, что можно и параметрами задавать.

2018-01-23 22:14 UTC, Maksov commented on .travis.yml
> -language: bash
@Nklya это да. но как бы из-за того, что изначально в ветке начал создавать настройки травис. и решать конфликты проверки травис.

2018-01-23 22:20 UTC, Maksov commented
@Nklya  устранены замечания в соответствии с рекомендациями

2018-01-23 22:45 UTC, Maksov commented on ansible/playbooks/deploy.yml
> +  hosts: "{{ group_app_hosts }}"
@Nklya а чем тут не одинаковый.  как раз понятно, что на тестовом мы прогоняем код. а на продакшн уже оттестированный ставим. поэтому если я выполню -i environment/prod у меня playbook выполниться на всех группах. так как gce выдает и тестовое окружение, и продакшн. если б в другом случае разные настройки были тестового и продакшн в динамическом окружении, чтоб они не пересекались. то конечно городить не надо

2018-01-24 04:44 UTC, Maksov commented on ansible/playbooks/deploy.yml
> +  hosts: "{{ group_app_hosts }}"
Обратился к документации. Можно и так запускать действительно ansible-playbook playbooks/PLAYBOOK_NAME.yml --limit 'group1'

2018-01-24 08:21 UTC, Nklya commented on ansible/playbooks/deploy.yml
> +  hosts: "{{ group_app_hosts }}"
Во-первых, окружения можно разнести по разным проектам, тогда они не будут попадать друг на друга в динамик инвентори. 
Во-вторых, можно было использовать https://github.com/adammck/terraform-inventory и указывать ему нужный стейт.

В любом случае повторяю, что ты реализовал жуткий набор костылей и так делать не надо.

2018-01-24 08:33 UTC, Nklya approved these changes
Добрый день.

Максим, сейчас все относительно нормально.

Комментарий по пересекающимся хостам я написал ранее сегодня.

Остальные замечания ниже.

2018-01-24 08:33 UTC, Nklya commented on ansible/ansible.cfg
> +inventory = ~/ansible/environments/prod/gce.py
У тебя он прямо вот в хомяке лежит?

2018-01-24 08:33 UTC, Nklya commented on packer/app.json
> +            "script": "scripts/install_ruby.sh",
В предыдущем ДЗ у тебя здесь появился ансибл, а тут все вернулось взад?

2018-01-24 08:33 UTC, Nklya commented on packer/db.json
> +            "scripts": "scripts/install_mongodb.sh",
В предыдущем ДЗ у тебя здесь появился ансибл, а тут все вернулось взад?

2018-01-24 08:33 UTC, Nklya commented on ansible/playbooks/group_app_hosts.yml
> +group_app_hosts: tag_prod-app
А эти зачем остались?

2018-01-24 08:33 UTC, Nklya commented on ansible/playbooks/group_db_hosts.yml
> +group_db_hosts: tag_prod-db
А эти зачем остались?

2018-01-24 08:37 UTC, Nklya commented
И куда делся тревис из диффа?
Зачем его вообще было коммитить в мастер, а не в бранч?
Если для тестирования, то можно было написать 
```branches:
  only:
  - master
  - ansible-3```

2018-01-24 09:09 UTC, Maksov commented on packer/db.json
> +            "scripts": "scripts/install_mongodb.sh",
@Nklya для упрощения сделал. packer не мог найти установленный ansible

2018-01-24 09:13 UTC, Nklya commented on packer/db.json
> +            "scripts": "scripts/install_mongodb.sh",
В следующем дз будет опять ансибл, опять будешь переделывать?
Если не хочешь разобраться, почему пакер не находил ансибл, сделай себе packer/app_bash.json и db_bash.json с башем.

2018-01-24 09:21 UTC, Maksov commented on ansible/ansible.cfg
> +inventory = ~/ansible/environments/prod/gce.py
@Nklya потому что он у меня в WLS. показалось проще так установить чем непосредственно ansible на windows. так как не знаю сколько бы пришлось настраивать это все через Cygwin. и работало оно с packer и terraform.  потом я уже копирую в папку с проектом на windows. согласен что не очень. но собираюсь оптимизировать. чтоб версии не разнились.

2018-01-24 09:24 UTC, Maksov commented
@Nklya подумал идея в том, что любые коммиты в мастер проверяются travis, в том числе и пул реквесты, которые приходят к нему.

2018-01-24 09:24 UTC, Nklya commented
Вот когда он в мастер попадет, он будет проверять все. А в этом задании нужно было его добавить.

2018-01-24 09:42 UTC, merged

2018-01-24 09:45 UTC, Maksov commented on ansible/playbooks/deploy.yml
> +  hosts: "{{ group_app_hosts }}"
@Nklya согласен. в итоге это не значит, что на реальном проекте я б так делал. просто сейчас под ситуацию подстраивался